### ISSUE TITLE
Plugin (1.0.3) not working

### ISSUE THREAD

**Issue by NoSync** [voorhoede/datocms-plugin-chat-gpt#4]
**How to reproduce**

Go to any enabled fields, select any Text Options, Max Characters and Keywords, and this error pops out after clicking on Generate Text:

<img width="603" alt="Screenshot 2023-11-02 at 15 56 25" src="https://github.com/voorhoede/datocms-plugin-chat-gpt/assets/12558732/ac1f42c3-1fa8-416a-8b69-faa7b893965e">

I tried with davinci-002 and text-davinci-003 with several different working API keys, same result. I can't test gpt-3.5-turbo-instruct, as the endpoint can't be configured and I believe by default the legacy /v1/completions is used.

**Comment by velomovies** [comment]
Hi @NoSync, thanks for raising this issue and sorry for the wait. I tried to reproduce it, but it looks like that it works on our side. Can you give some more information about your Dato model, so I can create you exact environment. (Or send a video so I can see how it happens)

Thanks in advance, hopefully it can be fixed soon.

**Comment by NoSync** [comment]
Hi @velomovies, this is the model:

<img width="889" alt="Screenshot 2023-12-11 at 15 24 42" src="https://github.com/voorhoede/datocms-plugin-chat-gpt/assets/12558732/e7b259a3-dc51-405e-a0b8-812bf780c3c7">

The field where I enabled the plugin is _description_, which is a structured text field with these settings:

<img width="781" alt="Screenshot 2023-12-11 at 15 25 06" src="https://github.com/voorhoede/datocms-plugin-chat-gpt/assets/12558732/7e83c12d-6ca5-4de0-a832-2e22a3f53261">

When editing, it would appear like this:

<img width="792" alt="image" src="https://github.com/voorhoede/datocms-plugin-chat-gpt/assets/12558732/23c7971d-0bb5-40d5-b00e-db5f1e8fde23">

Thank you.

**Comment by velomovies** [comment]
Thanks again @NoSync, This should be fixed in version `1.1.0`. It was a problem with the structured text field which didn't get the right field data. 

If there is anything wrong, feel free to open a new issue!
